### ISSUE TITLE
shpencil

### ISSUE THREAD

**Issue by DUCKMAN2016** [zompiexx/wargames#2]
I'm getting this error code

**Comment by DUCKMAN2016** [comment]
sh: 1: aplay: not found  , i'm getting this error.

**Comment by zompiexx** [comment]
> sh: 1: aplay: not found , i'm getting this error.

What OS are you using? The source code has been written for Debian Linux, but could be ported other OS with a few tweaks. Assuming you are running Linux, from a Linux Terminal window, try running: aplay and see what happens. If you are running Mac OS, I have a work around.

**Comment by DUCKMAN2016** [comment]
> > sh: 1: aplay: not found , i'm getting this error.
> 
> What OS are you using? The source code has been written for Debian Linux, but could be ported other OS with a few tweaks. Assuming you are running Linux, from a Linux Terminal window, try running: aplay and see what happens. If you are running Mac OS, I have a work around.

Ty, for the reply, i just realized, it's all user error. I'm sure this is the problem, it works fine in linux, I'm getting this error in WSL-Ubuntu. I'm not sure about my 4p-cpm machine yet. Can I get the fix for those?

**Comment by zompiexx** [comment]
> > > sh: 1: aplay: not found , i'm getting this error.
> > 
> > 
> > What OS are you using? The source code has been written for Debian Linux, but could be ported other OS with a few tweaks. Assuming you are running Linux, from a Linux Terminal window, try running: aplay and see what happens. If you are running Mac OS, I have a work around.
> 
> Ty, for the reply, i just realized, it's all user error. I'm sure this is the problem, it works fine in linux, I'm getting this error in WSL-Ubuntu. I'm not sure about my 4p-cpm machine yet. Can I get the fix for those?

Yes, would not expect it to work in WSL-Ubuntu without a few tweaks, but could be done. Didn't understand the question re: CP/M machine? Please can you explain more.

**Comment by DUCKMAN2016** [comment]
My TRS-80 Model 4p. Do you know where and what the code tweaks for the WSL machine and maybe CP/M are?

**Comment by zompiexx** [comment]
> My TRS-80 Model 4p. Do you know where and what the code tweaks for the WSL machine and maybe CP/M are?

Let's start with the CP/M Machine. Assuming you intend to run Client/Server (hosting the Wargames software on a Linux machine), then all you should need is KERMIT (software) on the CP/M machine + a serial WiFi AT modem.

For the WSL Machine, you will need an equivalent to aplay. All aplay does is allow you to play audio to the soundcard, so a symbolic link called aplay could be created pointing to another player (that supports WAV files). I don't have WSL installed, so can't advise what to use here - but a simple command line tool is what you want.

Or, if you don't have a WiFi modem, just cheat - and run it all on the Linux machine?

If you want to talk through the options, send me an email to retrotechshed@gmail.com and we can arrange a call.

Cheers,

Andy
